//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CensusTakerWinFrom.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.10.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("database.db")]
        public string Database {
            get {
                return ((string)(this["Database"]));
            }
            set {
                this["Database"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0, 0, 0")]
        public global::System.Drawing.Rectangle AddressBookProperties {
            get {
                return ((global::System.Drawing.Rectangle)(this["AddressBookProperties"]));
            }
            set {
                this["AddressBookProperties"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0, 0, 0")]
        public global::System.Drawing.Rectangle PersonalAccountProperties {
            get {
                return ((global::System.Drawing.Rectangle)(this["PersonalAccountProperties"]));
            }
            set {
                this["PersonalAccountProperties"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0, 0, 0")]
        public global::System.Drawing.Rectangle OperationProperties {
            get {
                return ((global::System.Drawing.Rectangle)(this["OperationProperties"]));
            }
            set {
                this["OperationProperties"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0, 0, 0")]
        public global::System.Drawing.Rectangle MainProperties {
            get {
                return ((global::System.Drawing.Rectangle)(this["MainProperties"]));
            }
            set {
                this["MainProperties"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0, 0, 0")]
        public global::System.Drawing.Rectangle ZoomCheckProperties {
            get {
                return ((global::System.Drawing.Rectangle)(this["ZoomCheckProperties"]));
            }
            set {
                this["ZoomCheckProperties"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0, 0, 0")]
        public global::System.Drawing.Rectangle SettingPropertirs {
            get {
                return ((global::System.Drawing.Rectangle)(this["SettingPropertirs"]));
            }
            set {
                this["SettingPropertirs"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Сбербанк")]
        public string KeyString {
            get {
                return ((string)(this["KeyString"]));
            }
            set {
                this["KeyString"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ЛИЦЕВОЙ СЧЕТ|ЛИЦЕВОЙ|СЧЕТ")]
        public string KeyPersonalAcc {
            get {
                return ((string)(this["KeyPersonalAcc"]));
            }
            set {
                this["KeyPersonalAcc"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ДАТА ОПЕРАЦИИ (МСК)|ЧЕК ПО ОПЕРАЦИИ|ДАТА ОПЕРАЦИИ")]
        public string KeyDate {
            get {
                return ((string)(this["KeyDate"]));
            }
            set {
                this["KeyDate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ПРЕД. ПОКАЗАНИЯ")]
        public string KeyOld {
            get {
                return ((string)(this["KeyOld"]));
            }
            set {
                this["KeyOld"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ТЕК. ПОКАЗАНИЯ")]
        public string KeyNew {
            get {
                return ((string)(this["KeyNew"]));
            }
            set {
                this["KeyNew"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ПОЛУЧАТЕЛЬ ПЛАТЕЖА|ПОЛУЧАТЕЛЬ")]
        public string KeyCompany {
            get {
                return ((string)(this["KeyCompany"]));
            }
            set {
                this["KeyCompany"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("СУММА ОПЕРАЦИИ|СУММА ПЛАТЕЖА")]
        public string KeyTariff {
            get {
                return ((string)(this["KeyTariff"]));
            }
            set {
                this["KeyTariff"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("БИК|ИНН|КПП")]
        public string KeyCompanyEnd {
            get {
                return ((string)(this["KeyCompanyEnd"]));
            }
            set {
                this["KeyCompanyEnd"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string KeyMount {
            get {
                return ((string)(this["KeyMount"]));
            }
            set {
                this["KeyMount"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0, 0, 0")]
        public global::System.Drawing.Rectangle ReportPropertirs {
            get {
                return ((global::System.Drawing.Rectangle)(this["ReportPropertirs"]));
            }
            set {
                this["ReportPropertirs"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("image\\noimage.jpg")]
        public string NoImageFileStream {
            get {
                return ((string)(this["NoImageFileStream"]));
            }
            set {
                this["NoImageFileStream"] = value;
            }
        }
    }
}
